// Code generated by goyacc -o yacc/idl.go -p IdlExpr yacc/idl.y. DO NOT EDIT.

//line yacc/idl.y:2
package yacc

import __yyfmt__ "fmt"

//line yacc/idl.y:2
//go:generate goyacc -o idl.go -p "IdlExpr" idl.y
import (
	"github.com/bhbosman/Application/goidlgenerator/IdlDefinedTypes"
	"github.com/bhbosman/Application/goidlgenerator/MitchDefinedTypes"
	"github.com/bhbosman/Application/goidlgenerator/TempleteTypes"
	"github.com/bhbosman/Application/goidlgenerator/interfaces"
)

//line yacc/idl.y:73
type IdlExprSymType struct {
	yys          int
	Identifier   string
	IntegerValue int64
	StringValue  string
	FloatValue   float64
	ConstValue   interfaces.IConstantValue
	BoolValue    bool

	Member                *Member
	Declarator            interfaces.IDeclarator
	DefinedType           interfaces.IDefinedType
	DefinitionDeclaration interfaces.IDefinitionDeclaration
	Specification         []interfaces.IDefinitionDeclaration
}

const SingleLineComment = 57346
const Identifier = 57347
const Integer_literal = 57348
const Hex_literal = 57349
const Octet_literal = 57350
const Floating_pt_literal = 57351
const Fixed_pt_literal = 57352
const Character_literal = 57353
const Wide_character_literal = 57354
const String_literal = 57355
const Wide_string_literal = 57356
const Scope = 57357
const Shl = 57358
const Shr = 57359
const Whitespace = 57360
const Rwboolean = 57361
const Rwcase = 57362
const Rwchar = 57363
const Rwconst = 57364
const Rwdefault = 57365
const Rwdouble = 57366
const Rwenum = 57367
const RwFALSE = 57368
const Rwfixed = 57369
const Rwfloat = 57370
const Rwlong = 57371
const Rwmodule = 57372
const Rwnative = 57373
const Rwoctet = 57374
const Rwsequence = 57375
const Rwshort = 57376
const Rwstring = 57377
const Rwstruct = 57378
const Rwswitch = 57379
const RwTRUE = 57380
const Rwtypedef = 57381
const Rwunsigned = 57382
const Rwunion = 57383
const Rwvoid = 57384
const Rwwchar = 57385
const Rwwstring = 57386
const Rwbitfield = 57387
const RwMitchAlpha = 57388
const RwMitchBitField = 57389
const RwMitchByte = 57390
const RwMitchDate = 57391
const RwMitchTime = 57392
const RwMitchPrice04 = 57393
const RwMitchPrice08 = 57394
const RwMitchUInt08 = 57395
const RwMitchUInt16 = 57396
const RwMitchUInt32 = 57397
const RwMitchUInt64 = 57398

var IdlExprToknames = [...]string{
	"$end",
	"error",
	"$unk",
	"SingleLineComment",
	"Identifier",
	"Integer_literal",
	"Hex_literal",
	"Octet_literal",
	"Floating_pt_literal",
	"Fixed_pt_literal",
	"Character_literal",
	"Wide_character_literal",
	"String_literal",
	"Wide_string_literal",
	"Scope",
	"Shl",
	"Shr",
	"Whitespace",
	"Rwboolean",
	"Rwcase",
	"Rwchar",
	"Rwconst",
	"Rwdefault",
	"Rwdouble",
	"Rwenum",
	"RwFALSE",
	"Rwfixed",
	"Rwfloat",
	"Rwlong",
	"Rwmodule",
	"Rwnative",
	"Rwoctet",
	"Rwsequence",
	"Rwshort",
	"Rwstring",
	"Rwstruct",
	"Rwswitch",
	"RwTRUE",
	"Rwtypedef",
	"Rwunsigned",
	"Rwunion",
	"Rwvoid",
	"Rwwchar",
	"Rwwstring",
	"Rwbitfield",
	"RwMitchAlpha",
	"RwMitchBitField",
	"RwMitchByte",
	"RwMitchDate",
	"RwMitchTime",
	"RwMitchPrice04",
	"RwMitchPrice08",
	"RwMitchUInt08",
	"RwMitchUInt16",
	"RwMitchUInt32",
	"RwMitchUInt64",
	"';'",
	"'{'",
	"'}'",
	"'='",
	"'|'",
	"'^'",
	"'&'",
	"'+'",
	"'-'",
	"'*'",
	"'/'",
	"'%'",
	"'~'",
	"'('",
	"')'",
	"'<'",
	"'>'",
	"','",
	"':'",
	"'['",
	"']'",
}
var IdlExprStatenames = [...]string{}

const IdlExprEofCode = 1
const IdlExprErrCode = 2
const IdlExprInitialStackSize = 16

//line yacc/idl.y:854

//line yacctab:1
var IdlExprExca = [...]int{
	-1, 1,
	1, -1,
	-2, 0,
}

const IdlExprPrivate = 57344

const IdlExprLast = 462

var IdlExprAct = [...]int{

	161, 160, 232, 230, 122, 135, 136, 164, 129, 121,
	159, 126, 124, 128, 39, 152, 61, 131, 127, 106,
	3, 195, 69, 24, 125, 214, 153, 90, 2, 246,
	242, 86, 221, 88, 253, 190, 35, 187, 186, 251,
	30, 249, 33, 192, 247, 235, 191, 225, 150, 192,
	191, 189, 188, 255, 224, 223, 185, 181, 168, 115,
	52, 114, 113, 112, 103, 107, 107, 107, 102, 222,
	213, 176, 177, 178, 48, 171, 46, 165, 170, 43,
	21, 169, 93, 42, 44, 110, 111, 49, 92, 59,
	50, 22, 174, 175, 193, 60, 23, 120, 47, 51,
	94, 75, 76, 77, 78, 79, 80, 81, 82, 83,
	84, 85, 236, 148, 226, 117, 158, 116, 98, 69,
	244, 155, 154, 69, 157, 167, 27, 119, 26, 25,
	118, 105, 100, 101, 149, 8, 104, 101, 21, 162,
	24, 9, 180, 7, 15, 52, 62, 233, 179, 22,
	234, 107, 16, 109, 23, 173, 172, 99, 66, 48,
	38, 46, 37, 184, 156, 97, 196, 183, 69, 202,
	182, 201, 166, 96, 59, 91, 95, 72, 28, 71,
	60, 64, 203, 205, 36, 210, 211, 212, 208, 209,
	217, 206, 207, 200, 219, 204, 215, 198, 216, 199,
	220, 69, 218, 151, 108, 238, 231, 52, 138, 89,
	87, 139, 140, 141, 142, 144, 145, 229, 34, 31,
	228, 197, 20, 19, 13, 11, 227, 63, 147, 14,
	17, 18, 12, 5, 237, 240, 243, 69, 241, 239,
	146, 245, 6, 4, 1, 73, 52, 65, 248, 74,
	250, 70, 252, 32, 254, 29, 41, 55, 40, 57,
	48, 58, 46, 56, 53, 43, 133, 132, 67, 42,
	44, 134, 137, 49, 68, 59, 54, 143, 130, 123,
	10, 60, 0, 0, 47, 0, 0, 75, 76, 77,
	78, 79, 80, 81, 82, 83, 84, 85, 52, 138,
	194, 52, 139, 140, 141, 142, 144, 145, 0, 0,
	0, 0, 0, 0, 0, 48, 0, 46, 0, 147,
	43, 0, 0, 0, 42, 44, 0, 0, 49, 0,
	59, 146, 0, 0, 0, 0, 60, 0, 0, 47,
	0, 0, 75, 76, 77, 78, 79, 80, 81, 82,
	83, 84, 85, 52, 0, 163, 8, 0, 0, 21,
	0, 0, 0, 137, 7, 15, 0, 48, 0, 46,
	22, 0, 43, 16, 0, 23, 42, 44, 0, 0,
	49, 0, 59, 0, 0, 0, 0, 0, 60, 0,
	0, 47, 52, 0, 75, 76, 77, 78, 79, 80,
	81, 82, 83, 84, 85, 0, 48, 0, 46, 0,
	0, 43, 0, 0, 45, 42, 44, 0, 0, 49,
	0, 59, 50, 0, 0, 0, 0, 60, 0, 138,
	47, 51, 139, 140, 141, 142, 144, 145, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0, 0, 147,
	0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 146,
}
var IdlExprPact = [...]int{

	334, -1000, 334, -1000, 72, 71, 69, 173, 387, -1000,
	-1000, -1000, -1000, -1000, -1000, 141, 55, -1000, -1000, -1000,
	-1000, 171, 168, 160, -1000, -1000, -1000, -1000, 60, 152,
	-1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000,
	-1000, -1000, -1000, -1000, 108, -1000, -1000, -1000, -1000, -1000,
	-4, -8, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000,
	102, -1000, -1000, -1000, 148, 148, 148, -1000, -1000, -1000,
	-1000, -1000, -1000, -1000, -1000, -9, -1000, -1000, -1000, -1000,
	-1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000,
	-1000, -1000, -10, -11, -13, 59, 57, 93, 334, 37,
	-1000, -1000, 202, 202, -1000, 105, -26, -1000, -1000, -50,
	-26, -26, 202, 348, 202, 141, 141, 296, 7, 113,
	202, -15, -1000, 20, 16, 12, 139, 28, 5, -1000,
	293, -1000, -1000, -1000, -1000, -1000, -1000, 202, -1000, -1000,
	-1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -16, -1000,
	148, -50, -1000, 202, -17, -36, -1000, -22, -23, -24,
	-31, 34, 241, -1000, 141, 140, -1000, -1000, -1000, 202,
	202, 202, 202, 202, 202, 202, 202, 202, 202, -1000,
	-1, -1000, -26, -1000, -52, -1000, 202, -1000, 202, 141,
	-1000, 141, 141, 423, -1000, 348, -25, -2, -1000, -1000,
	-1000, -1000, 104, 16, 12, 139, 28, 28, 5, 5,
	-1000, -1000, -1000, -1000, -1000, -18, -19, -27, -28, -31,
	-1000, -1000, 56, -1000, -1000, 141, 127, -29, 53, -1000,
	127, 348, 127, 202, -45, 141, -1000, -1000, 63, 141,
	-1000, -46, -1000, -30, -1000, -31, -1000, 141, -33, 141,
	-35, 141, -40, 141, -20, -1000,
}
var IdlExprPgo = [...]int{

	0, 0, 280, 6, 17, 9, 4, 279, 12, 24,
	11, 18, 13, 8, 278, 277, 21, 7, 276, 164,
	210, 274, 268, 264, 33, 209, 31, 27, 175, 263,
	261, 259, 258, 257, 256, 5, 255, 253, 251, 249,
	247, 162, 160, 245, 244, 20, 28, 243, 242, 233,
	232, 231, 230, 141, 229, 227, 225, 1, 19, 10,
	224, 223, 222, 221, 220, 217, 3, 206, 205, 2,
	204, 203, 15,
}
var IdlExprR1 = [...]int{

	0, 44, 46, 46, 45, 45, 45, 47, 35, 49,
	36, 36, 36, 36, 36, 36, 36, 36, 36, 36,
	6, 7, 7, 8, 8, 9, 9, 10, 10, 10,
	11, 11, 11, 12, 12, 12, 12, 13, 13, 14,
	14, 14, 4, 4, 4, 3, 3, 3, 3, 3,
	3, 3, 3, 15, 15, 5, 48, 48, 48, 17,
	22, 22, 22, 22, 22, 22, 22, 22, 22, 22,
	22, 19, 19, 19, 21, 21, 21, 21, 21, 21,
	20, 20, 20, 26, 26, 32, 32, 32, 23, 18,
	33, 34, 34, 34, 29, 31, 30, 24, 25, 27,
	28, 40, 40, 40, 40, 40, 39, 38, 38, 41,
	41, 42, 42, 43, 37, 53, 53, 53, 50, 50,
	52, 52, 16, 16, 51, 60, 60, 61, 63, 63,
	63, 63, 64, 65, 65, 66, 67, 67, 69, 69,
	68, 62, 54, 59, 59, 70, 71, 71, 72, 2,
	1, 56, 55, 55, 55, 58, 58, 58, 57, 57,
	57,
}
var IdlExprR2 = [...]int{

	0, 1, 1, 2, 2, 2, 2, 5, 1, 5,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 3, 1, 3, 1, 3, 1, 3, 3,
	1, 3, 3, 1, 3, 3, 3, 2, 1, 1,
	1, 1, 1, 1, 3, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	4, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 2, 1, 1, 1, 1, 1, 1, 1,
	2, 1, 1, 1, 2, 2, 3, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 18, 6, 4, 4,
	1, 4, 1, 6, 1, 1, 1, 1, 1, 1,
	5, 4, 3, 2, 2, 1, 1, 9, 1, 1,
	1, 1, 1, 1, 2, 3, 1, 2, 3, 2,
	2, 2, 5, 1, 3, 2, 1, 2, 3, 2,
	1, 2, 2, 2, 2, 1, 1, 3, 3, 1,
	3,
}
var IdlExprChk = [...]int{

	-1000, -44, -46, -45, -47, -49, -48, 30, 22, -53,
	-2, -56, -50, -60, -54, 31, 39, -52, -51, -61,
	-62, 25, 36, 41, -45, 57, 57, 57, 5, -36,
	-26, -20, -37, -24, -25, -27, -28, -41, -42, -35,
	-32, -34, 28, 24, 29, 27, 21, 43, 19, 32,
	35, 44, 5, -23, -18, -33, -29, -31, -30, 34,
	40, -1, 5, -55, -19, -40, -53, -22, -21, -35,
	-38, -41, -42, -43, -39, 46, 47, 48, 49, 50,
	51, 52, 53, 54, 55, 56, -26, -20, -24, -25,
	-27, -28, 33, 27, 45, 5, 5, 5, 58, 5,
	24, 29, 72, 72, 34, 29, -58, -1, -70, 5,
	-58, -58, 72, 72, 72, 72, 58, 58, 37, -46,
	60, -5, -6, -7, -8, -9, -10, -11, -12, -13,
	-14, -4, 65, 64, 69, -35, -3, 70, 6, 9,
	10, 11, 12, -15, 13, 14, 38, 26, -5, 29,
	74, -71, -72, 76, -5, -17, -19, -5, -1, -59,
	-57, -1, -16, 59, -17, 70, 59, -6, 73, 61,
	62, 63, 17, 16, 64, 65, 66, 67, 68, -4,
	-6, 73, -58, -72, -5, 73, 74, 73, 74, 74,
	59, 74, 74, 60, 59, -16, -57, -63, -26, -24,
	-27, -35, 29, -8, -9, -10, -11, -11, -12, -12,
	-13, -13, -13, 71, 77, -5, -5, -1, -59, -57,
	-3, 57, 71, 73, 73, 74, 58, -1, -64, -65,
	-66, -67, -69, 20, 23, 74, 59, -66, -68, -17,
	-69, -6, 75, -1, 57, -57, 75, 74, -1, 74,
	-1, 74, -1, 74, -1, 73,
}
var IdlExprDef = [...]int{

	0, -2, 1, 2, 0, 0, 0, 0, 0, 56,
	57, 58, 115, 116, 117, 0, 0, 118, 119, 125,
	126, 0, 0, 0, 3, 4, 5, 6, 0, 0,
	10, 11, 12, 13, 14, 15, 16, 17, 18, 19,
	83, 84, 80, 81, 89, 114, 97, 98, 99, 100,
	110, 112, 8, 85, 86, 87, 91, 92, 93, 88,
	0, 149, 150, 151, 0, 0, 0, 71, 72, 73,
	101, 102, 103, 104, 105, 0, 61, 62, 63, 64,
	65, 66, 67, 68, 69, 70, 74, 75, 76, 77,
	78, 79, 0, 0, 0, 0, 124, 141, 0, 0,
	82, 90, 0, 0, 94, 95, 152, 155, 156, 150,
	153, 154, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 55, 20, 21, 23, 25, 27, 30, 33,
	0, 38, 39, 40, 41, 42, 43, 0, 45, 46,
	47, 48, 49, 50, 51, 52, 53, 54, 0, 96,
	0, 145, 146, 0, 0, 0, 59, 0, 0, 0,
	143, 159, 0, 121, 0, 0, 7, 9, 109, 0,
	0, 0, 0, 0, 0, 0, 0, 0, 0, 37,
	0, 111, 157, 147, 0, 60, 0, 108, 0, 0,
	142, 0, 0, 0, 120, 123, 0, 0, 128, 129,
	130, 131, 89, 22, 24, 26, 28, 29, 31, 32,
	34, 35, 36, 44, 148, 0, 0, 0, 144, 160,
	158, 122, 0, 107, 113, 0, 0, 0, 0, 132,
	133, 0, 136, 0, 0, 0, 127, 134, 0, 0,
	137, 0, 139, 0, 135, 140, 138, 0, 0, 0,
	0, 0, 0, 0, 0, 106,
}
var IdlExprTok1 = [...]int{

	1, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 68, 63, 3,
	70, 71, 66, 64, 74, 65, 3, 67, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 75, 57,
	72, 60, 73, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 76, 3, 77, 62, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 58, 61, 59, 69,
}
var IdlExprTok2 = [...]int{

	2, 3, 4, 5, 6, 7, 8, 9, 10, 11,
	12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
	22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
	32, 33, 34, 35, 36, 37, 38, 39, 40, 41,
	42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
	52, 53, 54, 55, 56,
}
var IdlExprTok3 = [...]int{
	0,
}

var IdlExprErrorMessages = [...]struct {
	state int
	token int
	msg   string
}{}

//line yaccpar:1

/*	parser for yacc output	*/

var (
	IdlExprDebug        = 0
	IdlExprErrorVerbose = false
)

type IdlExprLexer interface {
	Lex(lval *IdlExprSymType) int
	Error(s string)
}

type IdlExprParser interface {
	Parse(IdlExprLexer) int
	Lookahead() int
}

type IdlExprParserImpl struct {
	lval  IdlExprSymType
	stack [IdlExprInitialStackSize]IdlExprSymType
	char  int
}

func (p *IdlExprParserImpl) Lookahead() int {
	return p.char
}

func IdlExprNewParser() IdlExprParser {
	return &IdlExprParserImpl{}
}

const IdlExprFlag = -1000

func IdlExprTokname(c int) string {
	if c >= 1 && c-1 < len(IdlExprToknames) {
		if IdlExprToknames[c-1] != "" {
			return IdlExprToknames[c-1]
		}
	}
	return __yyfmt__.Sprintf("tok-%v", c)
}

func IdlExprStatname(s int) string {
	if s >= 0 && s < len(IdlExprStatenames) {
		if IdlExprStatenames[s] != "" {
			return IdlExprStatenames[s]
		}
	}
	return __yyfmt__.Sprintf("state-%v", s)
}

func IdlExprErrorMessage(state, lookAhead int) string {
	const TOKSTART = 4

	if !IdlExprErrorVerbose {
		return "syntax error"
	}

	for _, e := range IdlExprErrorMessages {
		if e.state == state && e.token == lookAhead {
			return "syntax error: " + e.msg
		}
	}

	res := "syntax error: unexpected " + IdlExprTokname(lookAhead)

	// To match Bison, suggest at most four expected tokens.
	expected := make([]int, 0, 4)

	// Look for shiftable tokens.
	base := IdlExprPact[state]
	for tok := TOKSTART; tok-1 < len(IdlExprToknames); tok++ {
		if n := base + tok; n >= 0 && n < IdlExprLast && IdlExprChk[IdlExprAct[n]] == tok {
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}
	}

	if IdlExprDef[state] == -2 {
		i := 0
		for IdlExprExca[i] != -1 || IdlExprExca[i+1] != state {
			i += 2
		}

		// Look for tokens that we accept or reduce.
		for i += 2; IdlExprExca[i] >= 0; i += 2 {
			tok := IdlExprExca[i]
			if tok < TOKSTART || IdlExprExca[i+1] == 0 {
				continue
			}
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}

		// If the default action is to accept or reduce, give up.
		if IdlExprExca[i+1] != 0 {
			return res
		}
	}

	for i, tok := range expected {
		if i == 0 {
			res += ", expecting "
		} else {
			res += " or "
		}
		res += IdlExprTokname(tok)
	}
	return res
}

func IdlExprlex1(lex IdlExprLexer, lval *IdlExprSymType) (char, token int) {
	token = 0
	char = lex.Lex(lval)
	if char <= 0 {
		token = IdlExprTok1[0]
		goto out
	}
	if char < len(IdlExprTok1) {
		token = IdlExprTok1[char]
		goto out
	}
	if char >= IdlExprPrivate {
		if char < IdlExprPrivate+len(IdlExprTok2) {
			token = IdlExprTok2[char-IdlExprPrivate]
			goto out
		}
	}
	for i := 0; i < len(IdlExprTok3); i += 2 {
		token = IdlExprTok3[i+0]
		if token == char {
			token = IdlExprTok3[i+1]
			goto out
		}
	}

out:
	if token == 0 {
		token = IdlExprTok2[1] /* unknown char */
	}
	if IdlExprDebug >= 3 {
		__yyfmt__.Printf("lex %s(%d)\n", IdlExprTokname(token), uint(char))
	}
	return char, token
}

func IdlExprParse(IdlExprlex IdlExprLexer) int {
	return IdlExprNewParser().Parse(IdlExprlex)
}

func (IdlExprrcvr *IdlExprParserImpl) Parse(IdlExprlex IdlExprLexer) int {
	var IdlExprn int
	var IdlExprVAL IdlExprSymType
	var IdlExprDollar []IdlExprSymType
	_ = IdlExprDollar // silence set and not used
	IdlExprS := IdlExprrcvr.stack[:]

	Nerrs := 0   /* number of errors */
	Errflag := 0 /* error recovery flag */
	IdlExprstate := 0
	IdlExprrcvr.char = -1
	IdlExprtoken := -1 // IdlExprrcvr.char translated into internal numbering
	defer func() {
		// Make sure we report no lookahead when not parsing.
		IdlExprstate = -1
		IdlExprrcvr.char = -1
		IdlExprtoken = -1
	}()
	IdlExprp := -1
	goto IdlExprstack

ret0:
	return 0

ret1:
	return 1

IdlExprstack:
	/* put a state and value onto the stack */
	if IdlExprDebug >= 4 {
		__yyfmt__.Printf("char %v in %v\n", IdlExprTokname(IdlExprtoken), IdlExprStatname(IdlExprstate))
	}

	IdlExprp++
	if IdlExprp >= len(IdlExprS) {
		nyys := make([]IdlExprSymType, len(IdlExprS)*2)
		copy(nyys, IdlExprS)
		IdlExprS = nyys
	}
	IdlExprS[IdlExprp] = IdlExprVAL
	IdlExprS[IdlExprp].yys = IdlExprstate

IdlExprnewstate:
	IdlExprn = IdlExprPact[IdlExprstate]
	if IdlExprn <= IdlExprFlag {
		goto IdlExprdefault /* simple state */
	}
	if IdlExprrcvr.char < 0 {
		IdlExprrcvr.char, IdlExprtoken = IdlExprlex1(IdlExprlex, &IdlExprrcvr.lval)
	}
	IdlExprn += IdlExprtoken
	if IdlExprn < 0 || IdlExprn >= IdlExprLast {
		goto IdlExprdefault
	}
	IdlExprn = IdlExprAct[IdlExprn]
	if IdlExprChk[IdlExprn] == IdlExprtoken { /* valid shift */
		IdlExprrcvr.char = -1
		IdlExprtoken = -1
		IdlExprVAL = IdlExprrcvr.lval
		IdlExprstate = IdlExprn
		if Errflag > 0 {
			Errflag--
		}
		goto IdlExprstack
	}

IdlExprdefault:
	/* default state action */
	IdlExprn = IdlExprDef[IdlExprstate]
	if IdlExprn == -2 {
		if IdlExprrcvr.char < 0 {
			IdlExprrcvr.char, IdlExprtoken = IdlExprlex1(IdlExprlex, &IdlExprrcvr.lval)
		}

		/* look through exception table */
		xi := 0
		for {
			if IdlExprExca[xi+0] == -1 && IdlExprExca[xi+1] == IdlExprstate {
				break
			}
			xi += 2
		}
		for xi += 2; ; xi += 2 {
			IdlExprn = IdlExprExca[xi+0]
			if IdlExprn < 0 || IdlExprn == IdlExprtoken {
				break
			}
		}
		IdlExprn = IdlExprExca[xi+1]
		if IdlExprn < 0 {
			goto ret0
		}
	}
	if IdlExprn == 0 {
		/* error ... attempt to resume parsing */
		switch Errflag {
		case 0: /* brand new error */
			IdlExprlex.Error(IdlExprErrorMessage(IdlExprstate, IdlExprtoken))
			Nerrs++
			if IdlExprDebug >= 1 {
				__yyfmt__.Printf("%s", IdlExprStatname(IdlExprstate))
				__yyfmt__.Printf(" saw %s\n", IdlExprTokname(IdlExprtoken))
			}
			fallthrough

		case 1, 2: /* incompletely recovered error ... try again */
			Errflag = 3

			/* find a state where "error" is a legal shift action */
			for IdlExprp >= 0 {
				IdlExprn = IdlExprPact[IdlExprS[IdlExprp].yys] + IdlExprErrCode
				if IdlExprn >= 0 && IdlExprn < IdlExprLast {
					IdlExprstate = IdlExprAct[IdlExprn] /* simulate a shift of "error" */
					if IdlExprChk[IdlExprstate] == IdlExprErrCode {
						goto IdlExprstack
					}
				}

				/* the current p has no shift on "error", pop stack */
				if IdlExprDebug >= 2 {
					__yyfmt__.Printf("error recovery pops state %d\n", IdlExprS[IdlExprp].yys)
				}
				IdlExprp--
			}
			/* there is no state on the stack with an error shift ... abort */
			goto ret1

		case 3: /* no shift yet; clobber input char */
			if IdlExprDebug >= 2 {
				__yyfmt__.Printf("error recovery discards %s\n", IdlExprTokname(IdlExprtoken))
			}
			if IdlExprtoken == IdlExprEofCode {
				goto ret1
			}
			IdlExprrcvr.char = -1
			IdlExprtoken = -1
			goto IdlExprnewstate /* try again in the same state */
		}
	}

	/* reduction by production IdlExprn */
	if IdlExprDebug >= 2 {
		__yyfmt__.Printf("reduce %v in:\n\t%v\n", IdlExprn, IdlExprStatname(IdlExprstate))
	}

	IdlExprnt := IdlExprn
	IdlExprpt := IdlExprp
	_ = IdlExprpt // guard against "declared and not used"

	IdlExprp -= IdlExprR2[IdlExprn]
	// IdlExprp is now the index of $0. Perform the default action. Iff the
	// reduced production is ε, $1 is possibly out of range.
	if IdlExprp+1 >= len(IdlExprS) {
		nyys := make([]IdlExprSymType, len(IdlExprS)*2)
		copy(nyys, IdlExprS)
		IdlExprS = nyys
	}
	IdlExprVAL = IdlExprS[IdlExprp+1]

	/* consult goto table to find next state */
	IdlExprn = IdlExprR1[IdlExprn]
	IdlExprg := IdlExprPgo[IdlExprn]
	IdlExprj := IdlExprg + IdlExprS[IdlExprp].yys + 1

	if IdlExprj >= IdlExprLast {
		IdlExprstate = IdlExprAct[IdlExprg]
	} else {
		IdlExprstate = IdlExprAct[IdlExprj]
		if IdlExprChk[IdlExprstate] != -IdlExprn {
			IdlExprstate = IdlExprAct[IdlExprg]
		}
	}
	// dummy call; replaced with literal code
	switch IdlExprnt {

	case 1:
		IdlExprDollar = IdlExprS[IdlExprpt-1 : IdlExprpt+1]
//line yacc/idl.y:159
		{
			IdlExprVAL.Specification = AddDefinitions(IdlExprDollar[1].DefinitionDeclaration)
			context, _ := GetIdlExprContext(IdlExprlex)
			context.specification = IdlExprVAL.Specification
		}
	case 2:
		IdlExprDollar = IdlExprS[IdlExprpt-1 : IdlExprpt+1]
//line yacc/idl.y:166
		{
			IdlExprVAL.DefinitionDeclaration = IdlExprDollar[1].DefinitionDeclaration
		}
	case 3:
		IdlExprDollar = IdlExprS[IdlExprpt-2 : IdlExprpt+1]
//line yacc/idl.y:169
		{
			IdlExprVAL.DefinitionDeclaration = IdlExprDollar[1].DefinitionDeclaration
			GetLast(IdlExprVAL.DefinitionDeclaration).SetNext(IdlExprDollar[2].DefinitionDeclaration)
		}
	case 4:
		IdlExprDollar = IdlExprS[IdlExprpt-2 : IdlExprpt+1]
//line yacc/idl.y:175
		{
			IdlExprVAL.DefinitionDeclaration = IdlExprDollar[1].DefinitionDeclaration
		}
	case 5:
		IdlExprDollar = IdlExprS[IdlExprpt-2 : IdlExprpt+1]
//line yacc/idl.y:178
		{
			IdlExprVAL.DefinitionDeclaration = IdlExprDollar[1].DefinitionDeclaration
		}
	case 6:
		IdlExprDollar = IdlExprS[IdlExprpt-2 : IdlExprpt+1]
//line yacc/idl.y:181
		{
			err := AddTypeDclToContext(IdlExprlex, IdlExprDollar[1].DefinitionDeclaration)
			if err != nil {
				SendError(IdlExprlex, "AddTypedefDcl error")
				return ErrorOnAddTypedefDcl
			}

			IdlExprVAL.DefinitionDeclaration = IdlExprDollar[1].DefinitionDeclaration
		}
	case 7:
		IdlExprDollar = IdlExprS[IdlExprpt-5 : IdlExprpt+1]
//line yacc/idl.y:191
		{
			IdlExprVAL.DefinitionDeclaration = IdlExprDollar[4].DefinitionDeclaration
		}
	case 8:
		IdlExprDollar = IdlExprS[IdlExprpt-1 : IdlExprpt+1]
//line yacc/idl.y:195
		{
			lex, err := GetIdlExprContext(IdlExprlex)
			if err == nil {
				definitionDeclaration := lex.FindScopeName(IdlExprDollar[1].Identifier)
				if definitionDeclaration == nil {
					IdlExprlex.Error(__yyfmt__.Sprintf("Value %v is not declared", IdlExprDollar[1].Identifier))
					return DefNotFound
				} else {
					IdlExprVAL.DefinedType = definitionDeclaration
				}
			} else {
				IdlExprlex.Error(__yyfmt__.Sprintf("GetIdlExprLex failure", IdlExprDollar[1].Identifier))
				return NoLex
			}
		}
	case 9:
		IdlExprDollar = IdlExprS[IdlExprpt-5 : IdlExprpt+1]
//line yacc/idl.y:229
		{
			IdlExprVAL.DefinitionDeclaration = Newconst_dcl()
		}
	case 10:
		IdlExprDollar = IdlExprS[IdlExprpt-1 : IdlExprpt+1]
//line yacc/idl.y:233
		{
			IdlExprVAL.DefinedType = IdlExprDollar[1].DefinedType
		}
	case 11:
		IdlExprDollar = IdlExprS[IdlExprpt-1 : IdlExprpt+1]
//line yacc/idl.y:236
		{
			IdlExprVAL.DefinedType = IdlExprDollar[1].DefinedType
		}
	case 12:
		IdlExprDollar = IdlExprS[IdlExprpt-1 : IdlExprpt+1]
//line yacc/idl.y:239
		{
			IdlExprVAL.DefinedType = IdlExprDollar[1].DefinedType
		}
	case 13:
		IdlExprDollar = IdlExprS[IdlExprpt-1 : IdlExprpt+1]
//line yacc/idl.y:242
		{
			IdlExprVAL.DefinedType = IdlExprDollar[1].DefinedType
		}
	case 14:
		IdlExprDollar = IdlExprS[IdlExprpt-1 : IdlExprpt+1]
//line yacc/idl.y:245
		{
			IdlExprVAL.DefinedType = IdlExprDollar[1].DefinedType
		}
	case 15:
		IdlExprDollar = IdlExprS[IdlExprpt-1 : IdlExprpt+1]
//line yacc/idl.y:248
		{
			IdlExprVAL.DefinedType = IdlExprDollar[1].DefinedType
		}
	case 16:
		IdlExprDollar = IdlExprS[IdlExprpt-1 : IdlExprpt+1]
//line yacc/idl.y:251
		{
			IdlExprVAL.DefinedType = IdlExprDollar[1].DefinedType
		}
	case 17:
		IdlExprDollar = IdlExprS[IdlExprpt-1 : IdlExprpt+1]
//line yacc/idl.y:254
		{
			IdlExprVAL.DefinedType = IdlExprDollar[1].DefinedType
		}
	case 18:
		IdlExprDollar = IdlExprS[IdlExprpt-1 : IdlExprpt+1]
//line yacc/idl.y:257
		{
			IdlExprVAL.DefinedType = IdlExprDollar[1].DefinedType
		}
	case 19:
		IdlExprDollar = IdlExprS[IdlExprpt-1 : IdlExprpt+1]
//line yacc/idl.y:260
		{
			IdlExprVAL.DefinedType = IdlExprDollar[1].DefinedType
		}
	case 20:
		IdlExprDollar = IdlExprS[IdlExprpt-1 : IdlExprpt+1]
//line yacc/idl.y:266
		{
			IdlExprVAL.IntegerValue = IdlExprDollar[1].IntegerValue
		}
	case 21:
		IdlExprDollar = IdlExprS[IdlExprpt-1 : IdlExprpt+1]
//line yacc/idl.y:271
		{
			IdlExprVAL.IntegerValue = IdlExprDollar[1].IntegerValue
		}
	case 22:
		IdlExprDollar = IdlExprS[IdlExprpt-3 : IdlExprpt+1]
//line yacc/idl.y:275
		{
			IdlExprVAL.IntegerValue = IdlExprDollar[1].IntegerValue
		}
	case 23:
		IdlExprDollar = IdlExprS[IdlExprpt-1 : IdlExprpt+1]
//line yacc/idl.y:280
		{
			IdlExprVAL.IntegerValue = IdlExprDollar[1].IntegerValue
		}
	case 24:
		IdlExprDollar = IdlExprS[IdlExprpt-3 : IdlExprpt+1]
//line yacc/idl.y:283
		{
			IdlExprVAL.IntegerValue = IdlExprDollar[1].IntegerValue
		}
	case 25:
		IdlExprDollar = IdlExprS[IdlExprpt-1 : IdlExprpt+1]
//line yacc/idl.y:288
		{
			IdlExprVAL.IntegerValue = IdlExprDollar[1].IntegerValue
		}
	case 26:
		IdlExprDollar = IdlExprS[IdlExprpt-3 : IdlExprpt+1]
//line yacc/idl.y:291
		{
			IdlExprVAL.IntegerValue = IdlExprDollar[1].IntegerValue
		}
	case 27:
		IdlExprDollar = IdlExprS[IdlExprpt-1 : IdlExprpt+1]
//line yacc/idl.y:297
		{
			IdlExprVAL.IntegerValue = IdlExprDollar[1].IntegerValue
		}
	case 28:
		IdlExprDollar = IdlExprS[IdlExprpt-3 : IdlExprpt+1]
//line yacc/idl.y:300
		{
			IdlExprVAL.IntegerValue = IdlExprDollar[1].IntegerValue
		}
	case 29:
		IdlExprDollar = IdlExprS[IdlExprpt-3 : IdlExprpt+1]
//line yacc/idl.y:303
		{
			IdlExprVAL.IntegerValue = IdlExprDollar[1].IntegerValue
		}
	case 30:
		IdlExprDollar = IdlExprS[IdlExprpt-1 : IdlExprpt+1]
//line yacc/idl.y:308
		{
			IdlExprVAL.IntegerValue = IdlExprDollar[1].IntegerValue
		}
	case 31:
		IdlExprDollar = IdlExprS[IdlExprpt-3 : IdlExprpt+1]
//line yacc/idl.y:311
		{
			IdlExprVAL.IntegerValue = IdlExprDollar[1].IntegerValue + IdlExprDollar[3].IntegerValue
		}
	case 32:
		IdlExprDollar = IdlExprS[IdlExprpt-3 : IdlExprpt+1]
//line yacc/idl.y:314
		{
			IdlExprVAL.IntegerValue = IdlExprDollar[1].IntegerValue - IdlExprDollar[3].IntegerValue
		}
	case 33:
		IdlExprDollar = IdlExprS[IdlExprpt-1 : IdlExprpt+1]
//line yacc/idl.y:319
		{
			IdlExprVAL.IntegerValue = IdlExprDollar[1].IntegerValue
		}
	case 34:
		IdlExprDollar = IdlExprS[IdlExprpt-3 : IdlExprpt+1]
//line yacc/idl.y:322
		{
			IdlExprVAL.IntegerValue = IdlExprDollar[1].IntegerValue * IdlExprDollar[3].IntegerValue
		}
	case 35:
		IdlExprDollar = IdlExprS[IdlExprpt-3 : IdlExprpt+1]
//line yacc/idl.y:325
		{
			IdlExprVAL.IntegerValue = IdlExprDollar[1].IntegerValue / IdlExprDollar[3].IntegerValue
		}
	case 36:
		IdlExprDollar = IdlExprS[IdlExprpt-3 : IdlExprpt+1]
//line yacc/idl.y:328
		{
			IdlExprVAL.IntegerValue = IdlExprDollar[1].IntegerValue % IdlExprDollar[3].IntegerValue
		}
	case 37:
		IdlExprDollar = IdlExprS[IdlExprpt-2 : IdlExprpt+1]
//line yacc/idl.y:333
		{
			value, ok := IdlExprDollar[2].ConstValue.Value().(int64)
			if ok {
				IdlExprVAL.IntegerValue = value
			} else {
				SendError(IdlExprlex, "Value must be an integer (int64)")
				return ErrorMustbeAnInt
			}
		}
	case 38:
		IdlExprDollar = IdlExprS[IdlExprpt-1 : IdlExprpt+1]
//line yacc/idl.y:342
		{
			value, ok := IdlExprDollar[1].ConstValue.Value().(int64)
			if ok {
				IdlExprVAL.IntegerValue = value
			} else {
				SendError(IdlExprlex, "Value must be an integer (int64)")
				return ErrorMustbeAnInt
			}
		}
	case 39:
		IdlExprDollar = IdlExprS[IdlExprpt-1 : IdlExprpt+1]
//line yacc/idl.y:353
		{
			IdlExprVAL.IntegerValue = -1
		}
	case 40:
		IdlExprDollar = IdlExprS[IdlExprpt-1 : IdlExprpt+1]
//line yacc/idl.y:356
		{
			IdlExprVAL.IntegerValue = 0
		}
	case 41:
		IdlExprDollar = IdlExprS[IdlExprpt-1 : IdlExprpt+1]
//line yacc/idl.y:360
		{
			IdlExprVAL.IntegerValue = 99
		}
	case 42:
		IdlExprDollar = IdlExprS[IdlExprpt-1 : IdlExprpt+1]
//line yacc/idl.y:365
		{
			lex, err := GetIdlExprContext(IdlExprlex)
			if err == nil {
				data := lex.FindScopeName(IdlExprDollar[1].DefinedType.GetName())
				if data == nil {
					IdlExprlex.Error(__yyfmt__.Sprintf("Could not find defined value %v", IdlExprDollar[1].DefinedType.GetName()))
					return 10003
				}
			} else {
				IdlExprlex.Error("Could not find lex")
				return NoLex
			}
		}
	case 43:
		IdlExprDollar = IdlExprS[IdlExprpt-1 : IdlExprpt+1]
//line yacc/idl.y:378
		{
			IdlExprVAL.ConstValue = IdlExprDollar[1].ConstValue
		}
	case 44:
		IdlExprDollar = IdlExprS[IdlExprpt-3 : IdlExprpt+1]
//line yacc/idl.y:381
		{
			IdlExprVAL.ConstValue = newConstantValueWithNoLength(IdlExprDollar[2].IntegerValue, interfaces.Int64)
		}
	case 45:
		IdlExprDollar = IdlExprS[IdlExprpt-1 : IdlExprpt+1]
//line yacc/idl.y:386
		{
			IdlExprVAL.ConstValue = newConstantValueWithNoLength(IdlExprDollar[1].IntegerValue, interfaces.Int64)
		}
	case 46:
		IdlExprDollar = IdlExprS[IdlExprpt-1 : IdlExprpt+1]
//line yacc/idl.y:389
		{
			IdlExprVAL.ConstValue = nil
		}
	case 47:
		IdlExprDollar = IdlExprS[IdlExprpt-1 : IdlExprpt+1]
//line yacc/idl.y:392
		{
			IdlExprVAL.ConstValue = nil
		}
	case 48:
		IdlExprDollar = IdlExprS[IdlExprpt-1 : IdlExprpt+1]
//line yacc/idl.y:395
		{
			IdlExprVAL.ConstValue = newConstantValue(IdlExprDollar[1].StringValue, interfaces.Char, 1)
		}
	case 49:
		IdlExprDollar = IdlExprS[IdlExprpt-1 : IdlExprpt+1]
//line yacc/idl.y:398
		{
			IdlExprVAL.ConstValue = newConstantValue(IdlExprDollar[1].StringValue, interfaces.WChar, 1)
		}
	case 50:
		IdlExprDollar = IdlExprS[IdlExprpt-1 : IdlExprpt+1]
//line yacc/idl.y:401
		{
			IdlExprVAL.ConstValue = newConstantValueWithNoLength(IdlExprDollar[1].BoolValue, interfaces.Bool)
		}
	case 51:
		IdlExprDollar = IdlExprS[IdlExprpt-1 : IdlExprpt+1]
//line yacc/idl.y:404
		{
			IdlExprVAL.ConstValue = newConstantValueWithNoLength(IdlExprDollar[1].StringValue, interfaces.String)
		}
	case 52:
		IdlExprDollar = IdlExprS[IdlExprpt-1 : IdlExprpt+1]
//line yacc/idl.y:407
		{
			IdlExprVAL.ConstValue = newConstantValueWithNoLength(IdlExprDollar[1].StringValue, interfaces.WideString)
		}
	case 53:
		IdlExprDollar = IdlExprS[IdlExprpt-1 : IdlExprpt+1]
//line yacc/idl.y:412
		{
			IdlExprVAL.BoolValue = true
		}
	case 54:
		IdlExprDollar = IdlExprS[IdlExprpt-1 : IdlExprpt+1]
//line yacc/idl.y:415
		{
			IdlExprVAL.BoolValue = false
		}
	case 56:
		IdlExprDollar = IdlExprS[IdlExprpt-1 : IdlExprpt+1]
//line yacc/idl.y:422
		{
			IdlExprVAL.DefinitionDeclaration = IdlExprDollar[1].DefinitionDeclaration
		}
	case 57:
		IdlExprDollar = IdlExprS[IdlExprpt-1 : IdlExprpt+1]
//line yacc/idl.y:425
		{
			nativeDecl := NewNativeDeclaration(IdlExprDollar[1].Identifier)
			IdlExprVAL.DefinitionDeclaration = nativeDecl
		}
	case 58:
		IdlExprDollar = IdlExprS[IdlExprpt-1 : IdlExprpt+1]
//line yacc/idl.y:429
		{

			if typeDecl, ok := IdlExprDollar[1].DefinitionDeclaration.(interfaces.ITypeDeclaration); ok {
				err := AddTypedefDcl(IdlExprlex, typeDecl)
				if err != nil {
					SendError(IdlExprlex, "AddTypedefDcl error")
					return ErrorOnAddTypedefDcl
				}
			} else {
				SendError(IdlExprlex, "AddTypedefDcl error")
				return ErrorOnAddTypedefDcl
			}

		}
	case 59:
		IdlExprDollar = IdlExprS[IdlExprpt-1 : IdlExprpt+1]
//line yacc/idl.y:444
		{
			IdlExprVAL.DefinedType = IdlExprDollar[1].DefinedType
		}
	case 60:
		IdlExprDollar = IdlExprS[IdlExprpt-4 : IdlExprpt+1]
//line yacc/idl.y:449
		{
			IdlExprVAL.DefinedType = MitchDefinedTypes.NewMitchAlpha(IdlExprDollar[3].IntegerValue)
		}
	case 61:
		IdlExprDollar = IdlExprS[IdlExprpt-1 : IdlExprpt+1]
//line yacc/idl.y:452
		{
			IdlExprVAL.DefinedType = MitchDefinedTypes.NewMitchBitField()
		}
	case 62:
		IdlExprDollar = IdlExprS[IdlExprpt-1 : IdlExprpt+1]
//line yacc/idl.y:455
		{
			IdlExprVAL.DefinedType = MitchDefinedTypes.NewMitchByte()
		}
	case 63:
		IdlExprDollar = IdlExprS[IdlExprpt-1 : IdlExprpt+1]
//line yacc/idl.y:458
		{
			IdlExprVAL.DefinedType = MitchDefinedTypes.NewMitchDate()
		}
	case 64:
		IdlExprDollar = IdlExprS[IdlExprpt-1 : IdlExprpt+1]
//line yacc/idl.y:461
		{
			IdlExprVAL.DefinedType = MitchDefinedTypes.NewMitchTime()
		}
	case 65:
		IdlExprDollar = IdlExprS[IdlExprpt-1 : IdlExprpt+1]
//line yacc/idl.y:464
		{
			IdlExprVAL.DefinedType = MitchDefinedTypes.NewMitchPrice04()
		}
	case 66:
		IdlExprDollar = IdlExprS[IdlExprpt-1 : IdlExprpt+1]
//line yacc/idl.y:467
		{
			IdlExprVAL.DefinedType = MitchDefinedTypes.NewMitchPrice08()
		}
	case 67:
		IdlExprDollar = IdlExprS[IdlExprpt-1 : IdlExprpt+1]
//line yacc/idl.y:470
		{
			IdlExprVAL.DefinedType = MitchDefinedTypes.NewMitchUInt08()
		}
	case 68:
		IdlExprDollar = IdlExprS[IdlExprpt-1 : IdlExprpt+1]
//line yacc/idl.y:473
		{
			IdlExprVAL.DefinedType = MitchDefinedTypes.NewMitchUInt16()
		}
	case 69:
		IdlExprDollar = IdlExprS[IdlExprpt-1 : IdlExprpt+1]
//line yacc/idl.y:476
		{
			IdlExprVAL.DefinedType = MitchDefinedTypes.NewMitchUInt32()
		}
	case 70:
		IdlExprDollar = IdlExprS[IdlExprpt-1 : IdlExprpt+1]
//line yacc/idl.y:479
		{
			IdlExprVAL.DefinedType = MitchDefinedTypes.NewMitchUInt64()
		}
	case 71:
		IdlExprDollar = IdlExprS[IdlExprpt-1 : IdlExprpt+1]
//line yacc/idl.y:484
		{
			context, err := GetIdlExprLex(IdlExprlex)
			if err != nil {
				IdlExprlex.Error(__yyfmt__.Sprintf("GetIdlExprLex failure"))
				return NoLex
			}
			if context.IDlBaseType.Name() != interfaces.IDlBaseType_Mitch {
				IdlExprlex.Error(__yyfmt__.Sprintf("IDlBaseType not set to IDlBaseType_Micth. %v is an invalid token", IdlExprDollar[1].DefinedType.GetName()))
				return NoLex

			}
			IdlExprVAL.DefinedType = IdlExprDollar[1].DefinedType
		}
	case 72:
		IdlExprDollar = IdlExprS[IdlExprpt-1 : IdlExprpt+1]
//line yacc/idl.y:499
		{
			context, err := GetIdlExprLex(IdlExprlex)
			if err != nil {
				IdlExprlex.Error(__yyfmt__.Sprintf("GetIdlExprLex failure"))
				return NoLex
			}

			if context.IDlBaseType.Name() != interfaces.IDlBaseType_Native {
				IdlExprlex.Error(__yyfmt__.Sprintf("IDlBaseType not set to IDlBaseType_Native. %v is an invalid token", IdlExprDollar[1].DefinedType))
				return NoLex

			}
			IdlExprVAL.DefinedType = IdlExprDollar[1].DefinedType
		}
	case 73:
		IdlExprDollar = IdlExprS[IdlExprpt-1 : IdlExprpt+1]
//line yacc/idl.y:513
		{
			IdlExprVAL.DefinedType = IdlExprDollar[1].DefinedType
			context, err := GetIdlExprLex(IdlExprlex)
			if err != nil {
				IdlExprlex.Error(__yyfmt__.Sprintf("GetIdlExprLex failure"))
				return NoLex
			}

			if !context.IDlBaseType.CanScope(IdlExprDollar[1].DefinedType) {
				IdlExprlex.Error(__yyfmt__.Sprintf("No scoping allowed. %v is an invalid token", IdlExprDollar[1].DefinedType.GetName()))
				return ErrorNoScopingAllowed
			}
			IdlExprVAL.DefinedType = IdlExprDollar[1].DefinedType

		}
	case 74:
		IdlExprDollar = IdlExprS[IdlExprpt-1 : IdlExprpt+1]
//line yacc/idl.y:531
		{
			IdlExprVAL.DefinedType = IdlExprDollar[1].DefinedType
		}
	case 75:
		IdlExprDollar = IdlExprS[IdlExprpt-1 : IdlExprpt+1]
//line yacc/idl.y:534
		{
			IdlExprVAL.DefinedType = IdlExprDollar[1].DefinedType
		}
	case 76:
		IdlExprDollar = IdlExprS[IdlExprpt-1 : IdlExprpt+1]
//line yacc/idl.y:537
		{
			IdlExprVAL.DefinedType = IdlExprDollar[1].DefinedType
		}
	case 77:
		IdlExprDollar = IdlExprS[IdlExprpt-1 : IdlExprpt+1]
//line yacc/idl.y:540
		{
			IdlExprVAL.DefinedType = IdlExprDollar[1].DefinedType
		}
	case 78:
		IdlExprDollar = IdlExprS[IdlExprpt-1 : IdlExprpt+1]
//line yacc/idl.y:543
		{
			IdlExprVAL.DefinedType = IdlExprDollar[1].DefinedType
		}
	case 79:
		IdlExprDollar = IdlExprS[IdlExprpt-1 : IdlExprpt+1]
//line yacc/idl.y:546
		{
			IdlExprVAL.DefinedType = IdlExprDollar[1].DefinedType
		}
	case 80:
		IdlExprDollar = IdlExprS[IdlExprpt-1 : IdlExprpt+1]
//line yacc/idl.y:550
		{
			IdlExprVAL.DefinedType = IdlDefinedTypes.NewFloatType()
		}
	case 81:
		IdlExprDollar = IdlExprS[IdlExprpt-1 : IdlExprpt+1]
//line yacc/idl.y:553
		{
			IdlExprVAL.DefinedType = IdlDefinedTypes.NewDoubleType()
		}
	case 82:
		IdlExprDollar = IdlExprS[IdlExprpt-2 : IdlExprpt+1]
//line yacc/idl.y:556
		{
			IdlExprVAL.DefinedType = IdlDefinedTypes.NewLongDoubleType()
		}
	case 83:
		IdlExprDollar = IdlExprS[IdlExprpt-1 : IdlExprpt+1]
//line yacc/idl.y:560
		{
			IdlExprVAL.DefinedType = IdlExprDollar[1].DefinedType
		}
	case 84:
		IdlExprDollar = IdlExprS[IdlExprpt-1 : IdlExprpt+1]
//line yacc/idl.y:563
		{
			IdlExprVAL.DefinedType = IdlExprDollar[1].DefinedType
		}
	case 85:
		IdlExprDollar = IdlExprS[IdlExprpt-1 : IdlExprpt+1]
//line yacc/idl.y:567
		{
			IdlExprVAL.DefinedType = IdlExprDollar[1].DefinedType
		}
	case 86:
		IdlExprDollar = IdlExprS[IdlExprpt-1 : IdlExprpt+1]
//line yacc/idl.y:570
		{
			IdlExprVAL.DefinedType = IdlExprDollar[1].DefinedType
		}
	case 87:
		IdlExprDollar = IdlExprS[IdlExprpt-1 : IdlExprpt+1]
//line yacc/idl.y:573
		{
			IdlExprVAL.DefinedType = IdlExprDollar[1].DefinedType
		}
	case 88:
		IdlExprDollar = IdlExprS[IdlExprpt-1 : IdlExprpt+1]
//line yacc/idl.y:577
		{
			IdlExprVAL.DefinedType = IdlDefinedTypes.NewSignedShortType()
		}
	case 89:
		IdlExprDollar = IdlExprS[IdlExprpt-1 : IdlExprpt+1]
//line yacc/idl.y:581
		{
			IdlExprVAL.DefinedType = IdlDefinedTypes.NewSignedLongType()
		}
	case 90:
		IdlExprDollar = IdlExprS[IdlExprpt-2 : IdlExprpt+1]
//line yacc/idl.y:585
		{
			IdlExprVAL.DefinedType = IdlDefinedTypes.NewSignedLongLongType()
		}
	case 91:
		IdlExprDollar = IdlExprS[IdlExprpt-1 : IdlExprpt+1]
//line yacc/idl.y:590
		{
			IdlExprVAL.DefinedType = IdlExprDollar[1].DefinedType
		}
	case 92:
		IdlExprDollar = IdlExprS[IdlExprpt-1 : IdlExprpt+1]
//line yacc/idl.y:593
		{
			IdlExprVAL.DefinedType = IdlExprDollar[1].DefinedType
		}
	case 93:
		IdlExprDollar = IdlExprS[IdlExprpt-1 : IdlExprpt+1]
//line yacc/idl.y:596
		{
			IdlExprVAL.DefinedType = IdlExprDollar[1].DefinedType
		}
	case 94:
		IdlExprDollar = IdlExprS[IdlExprpt-2 : IdlExprpt+1]
//line yacc/idl.y:601
		{
			IdlExprVAL.DefinedType = IdlDefinedTypes.NewUnSignedShortType()
		}
	case 95:
		IdlExprDollar = IdlExprS[IdlExprpt-2 : IdlExprpt+1]
//line yacc/idl.y:605
		{
			IdlExprVAL.DefinedType = IdlDefinedTypes.NewUnsignedLongType()
		}
	case 96:
		IdlExprDollar = IdlExprS[IdlExprpt-3 : IdlExprpt+1]
//line yacc/idl.y:609
		{
			IdlExprVAL.DefinedType = IdlDefinedTypes.NewUnsignedLongLongType()
		}
	case 97:
		IdlExprDollar = IdlExprS[IdlExprpt-1 : IdlExprpt+1]
//line yacc/idl.y:614
		{
			IdlExprVAL.DefinedType = IdlDefinedTypes.NewCharType()
		}
	case 98:
		IdlExprDollar = IdlExprS[IdlExprpt-1 : IdlExprpt+1]
//line yacc/idl.y:619
		{
			IdlExprVAL.DefinedType = IdlDefinedTypes.NewWideCharType()
		}
	case 99:
		IdlExprDollar = IdlExprS[IdlExprpt-1 : IdlExprpt+1]
//line yacc/idl.y:623
		{
			IdlExprVAL.DefinedType = IdlDefinedTypes.NewBooleanType()
		}
	case 100:
		IdlExprDollar = IdlExprS[IdlExprpt-1 : IdlExprpt+1]
//line yacc/idl.y:628
		{
			IdlExprVAL.DefinedType = IdlDefinedTypes.NewOctetType()
		}
	case 101:
		IdlExprDollar = IdlExprS[IdlExprpt-1 : IdlExprpt+1]
//line yacc/idl.y:633
		{
			IdlExprVAL.DefinedType = IdlExprDollar[1].DefinedType
		}
	case 102:
		IdlExprDollar = IdlExprS[IdlExprpt-1 : IdlExprpt+1]
//line yacc/idl.y:636
		{
			IdlExprVAL.DefinedType = IdlExprDollar[1].DefinedType
		}
	case 103:
		IdlExprDollar = IdlExprS[IdlExprpt-1 : IdlExprpt+1]
//line yacc/idl.y:639
		{
			IdlExprVAL.DefinedType = IdlExprDollar[1].DefinedType
		}
	case 104:
		IdlExprDollar = IdlExprS[IdlExprpt-1 : IdlExprpt+1]
//line yacc/idl.y:642
		{
			IdlExprVAL.DefinedType = IdlExprDollar[1].DefinedType
		}
	case 105:
		IdlExprDollar = IdlExprS[IdlExprpt-1 : IdlExprpt+1]
//line yacc/idl.y:645
		{
			IdlExprVAL.DefinedType = IdlExprDollar[1].DefinedType
		}
	case 106:
		IdlExprDollar = IdlExprS[IdlExprpt-18 : IdlExprpt+1]
//line yacc/idl.y:650
		{
			IdlExprVAL.DefinedType = NewBitField(IdlExprDollar[3].Identifier, IdlExprDollar[5].Identifier, IdlExprDollar[7].Identifier, IdlExprDollar[9].Identifier, IdlExprDollar[11].Identifier, IdlExprDollar[13].Identifier, IdlExprDollar[15].Identifier, IdlExprDollar[17].Identifier)
		}
	case 107:
		IdlExprDollar = IdlExprS[IdlExprpt-6 : IdlExprpt+1]
//line yacc/idl.y:656
		{
			IdlExprVAL.DefinedType = TempleteTypes.NewSequenceType(IdlExprDollar[3].DefinedType, IdlExprDollar[5].IntegerValue)
		}
	case 108:
		IdlExprDollar = IdlExprS[IdlExprpt-4 : IdlExprpt+1]
//line yacc/idl.y:659
		{
			IdlExprVAL.DefinedType = TempleteTypes.NewSequenceType(IdlExprDollar[3].DefinedType, -1)
		}
	case 109:
		IdlExprDollar = IdlExprS[IdlExprpt-4 : IdlExprpt+1]
//line yacc/idl.y:664
		{
			IdlExprVAL.DefinedType = IdlDefinedTypes.NewStringType(IdlExprDollar[3].IntegerValue)
		}
	case 110:
		IdlExprDollar = IdlExprS[IdlExprpt-1 : IdlExprpt+1]
//line yacc/idl.y:668
		{
			IdlExprVAL.DefinedType = IdlDefinedTypes.NewStringType(-1)
		}
	case 111:
		IdlExprDollar = IdlExprS[IdlExprpt-4 : IdlExprpt+1]
//line yacc/idl.y:673
		{
			IdlExprVAL.DefinedType = IdlDefinedTypes.NewWideStringType(IdlExprDollar[3].IntegerValue)
		}
	case 112:
		IdlExprDollar = IdlExprS[IdlExprpt-1 : IdlExprpt+1]
//line yacc/idl.y:676
		{
			IdlExprVAL.DefinedType = IdlDefinedTypes.NewWideStringType(-1)
		}
	case 113:
		IdlExprDollar = IdlExprS[IdlExprpt-6 : IdlExprpt+1]
//line yacc/idl.y:682
		{
			IdlExprVAL.DefinedType = IdlDefinedTypes.NewFixedType()
		}
	case 114:
		IdlExprDollar = IdlExprS[IdlExprpt-1 : IdlExprpt+1]
//line yacc/idl.y:687
		{
			IdlExprVAL.DefinedType = IdlDefinedTypes.NewFixedType()
		}
	case 115:
		IdlExprDollar = IdlExprS[IdlExprpt-1 : IdlExprpt+1]
//line yacc/idl.y:692
		{
			IdlExprVAL.DefinitionDeclaration = IdlExprDollar[1].DefinitionDeclaration
		}
	case 116:
		IdlExprDollar = IdlExprS[IdlExprpt-1 : IdlExprpt+1]
//line yacc/idl.y:695
		{
			IdlExprVAL.DefinitionDeclaration = Newunion_dcl()
		}
	case 117:
		IdlExprDollar = IdlExprS[IdlExprpt-1 : IdlExprpt+1]
//line yacc/idl.y:698
		{
			IdlExprVAL.DefinitionDeclaration = IdlExprDollar[1].DefinitionDeclaration
		}
	case 118:
		IdlExprDollar = IdlExprS[IdlExprpt-1 : IdlExprpt+1]
//line yacc/idl.y:706
		{
			IdlExprVAL.DefinitionDeclaration = IdlExprDollar[1].DefinitionDeclaration

		}
	case 119:
		IdlExprDollar = IdlExprS[IdlExprpt-1 : IdlExprpt+1]
//line yacc/idl.y:710
		{
			IdlExprVAL.DefinitionDeclaration = IdlExprDollar[1].DefinitionDeclaration
		}
	case 120:
		IdlExprDollar = IdlExprS[IdlExprpt-5 : IdlExprpt+1]
//line yacc/idl.y:716
		{
			def := NewStructDefinition(IdlExprDollar[2].Identifier)
			member := IdlExprDollar[4].Member
			for member != nil {
				decl := member.Declarator
				for decl != nil {
					def.AddMember(member.DefinedType, decl)
					decl = decl.Next()
				}
				member = member.Next
			}
			IdlExprVAL.DefinitionDeclaration = def
		}
	case 121:
		IdlExprDollar = IdlExprS[IdlExprpt-4 : IdlExprpt+1]
//line yacc/idl.y:729
		{
			def := NewStructDefinition(IdlExprDollar[2].Identifier)
			IdlExprVAL.DefinitionDeclaration = def
		}
	case 122:
		IdlExprDollar = IdlExprS[IdlExprpt-3 : IdlExprpt+1]
//line yacc/idl.y:736
		{
			IdlExprVAL.Member = NewMember(IdlExprDollar[1].DefinedType, IdlExprDollar[2].Declarator, nil)
		}
	case 123:
		IdlExprDollar = IdlExprS[IdlExprpt-2 : IdlExprpt+1]
//line yacc/idl.y:739
		{
			IdlExprVAL.Member = NewMember(IdlExprDollar[1].Member.DefinedType, IdlExprDollar[1].Member.Declarator, IdlExprDollar[2].Member)
		}
	case 124:
		IdlExprDollar = IdlExprS[IdlExprpt-2 : IdlExprpt+1]
//line yacc/idl.y:746
		{
			IdlExprVAL.DefinitionDeclaration = Newstruct_forward_dcl()
		}
	case 142:
		IdlExprDollar = IdlExprS[IdlExprpt-5 : IdlExprpt+1]
//line yacc/idl.y:761
		{
			def := NewEnumDcl(IdlExprDollar[2].Identifier)
			decl := IdlExprDollar[4].Declarator
			for decl != nil {
				def.AddMember(decl)
				decl = decl.Next()
			}
			IdlExprVAL.DefinitionDeclaration = def
		}
	case 143:
		IdlExprDollar = IdlExprS[IdlExprpt-1 : IdlExprpt+1]
//line yacc/idl.y:771
		{
		}
	case 144:
		IdlExprDollar = IdlExprS[IdlExprpt-3 : IdlExprpt+1]
//line yacc/idl.y:772
		{
			IdlExprDollar[1].Declarator.SetNext(IdlExprDollar[3].Declarator)
		}
	case 145:
		IdlExprDollar = IdlExprS[IdlExprpt-2 : IdlExprpt+1]
//line yacc/idl.y:778
		{

		}
	case 146:
		IdlExprDollar = IdlExprS[IdlExprpt-1 : IdlExprpt+1]
//line yacc/idl.y:783
		{

		}
	case 147:
		IdlExprDollar = IdlExprS[IdlExprpt-2 : IdlExprpt+1]
//line yacc/idl.y:786
		{

		}
	case 148:
		IdlExprDollar = IdlExprS[IdlExprpt-3 : IdlExprpt+1]
//line yacc/idl.y:791
		{
		}
	case 149:
		IdlExprDollar = IdlExprS[IdlExprpt-2 : IdlExprpt+1]
//line yacc/idl.y:795
		{
			IdlExprVAL.Identifier = IdlExprDollar[2].Identifier
		}
	case 150:
		IdlExprDollar = IdlExprS[IdlExprpt-1 : IdlExprpt+1]
//line yacc/idl.y:800
		{
			IdlExprVAL.Identifier = IdlExprDollar[1].Identifier
		}
	case 151:
		IdlExprDollar = IdlExprS[IdlExprpt-2 : IdlExprpt+1]
//line yacc/idl.y:805
		{
			IdlExprVAL.DefinitionDeclaration = IdlExprDollar[2].DefinitionDeclaration
		}
	case 152:
		IdlExprDollar = IdlExprS[IdlExprpt-2 : IdlExprpt+1]
//line yacc/idl.y:814
		{
			IdlExprVAL.DefinitionDeclaration = Newtypedef_dcl(IdlExprDollar[1].DefinedType, IdlExprDollar[2].Declarator)
		}
	case 153:
		IdlExprDollar = IdlExprS[IdlExprpt-2 : IdlExprpt+1]
//line yacc/idl.y:817
		{
			IdlExprVAL.DefinitionDeclaration = Newtypedef_dcl(IdlExprDollar[1].DefinedType, IdlExprDollar[2].Declarator)
		}
	case 154:
		IdlExprDollar = IdlExprS[IdlExprpt-2 : IdlExprpt+1]
//line yacc/idl.y:820
		{
			IdlExprVAL.DefinitionDeclaration = Newtypedef_dcl(IdlExprDollar[1].DefinitionDeclaration, IdlExprDollar[2].Declarator)
		}
	case 155:
		IdlExprDollar = IdlExprS[IdlExprpt-1 : IdlExprpt+1]
//line yacc/idl.y:829
		{
			IdlExprVAL.Declarator = NewDeclarator(IdlExprDollar[1].Identifier, nil)
		}
	case 156:
		IdlExprDollar = IdlExprS[IdlExprpt-1 : IdlExprpt+1]
//line yacc/idl.y:832
		{

		}
	case 157:
		IdlExprDollar = IdlExprS[IdlExprpt-3 : IdlExprpt+1]
//line yacc/idl.y:835
		{
			IdlExprDollar[1].Declarator.SetNext(IdlExprDollar[3].Declarator)
			IdlExprVAL.Declarator = IdlExprDollar[1].Declarator
		}
	case 158:
		IdlExprDollar = IdlExprS[IdlExprpt-3 : IdlExprpt+1]
//line yacc/idl.y:844
		{
			IdlExprVAL.Declarator = NewDeclarator(IdlExprDollar[1].Identifier, IdlExprDollar[3].ConstValue)
		}
	case 159:
		IdlExprDollar = IdlExprS[IdlExprpt-1 : IdlExprpt+1]
//line yacc/idl.y:847
		{
			IdlExprVAL.Declarator = NewDeclarator(IdlExprDollar[1].Identifier, nil)
		}
	case 160:
		IdlExprDollar = IdlExprS[IdlExprpt-3 : IdlExprpt+1]
//line yacc/idl.y:850
		{
			IdlExprDollar[1].Declarator.SetNext(IdlExprDollar[3].Declarator)
			IdlExprVAL.Declarator = IdlExprDollar[1].Declarator
		}
	}
	goto IdlExprstack /* stack new state and value */
}
