// Code generated by MockGen. DO NOT EDIT.
// Source: IKeyBucket.go

// Package PubSub is a generated GoMock package.
package PubSub

import (
	gomock "github.com/golang/mock/gomock"
	reflect "reflect"
)

// MockIKeyBucket is a mock of IKeyBucket interface
type MockIKeyBucket struct {
	ctrl     *gomock.Controller
	recorder *MockIKeyBucketMockRecorder
}

// MockIKeyBucketMockRecorder is the mock recorder for MockIKeyBucket
type MockIKeyBucketMockRecorder struct {
	mock *MockIKeyBucket
}

// NewMockIKeyBucket creates a new mock instance
func NewMockIKeyBucket(ctrl *gomock.Controller) *MockIKeyBucket {
	mock := &MockIKeyBucket{ctrl: ctrl}
	mock.recorder = &MockIKeyBucketMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockIKeyBucket) EXPECT() *MockIKeyBucketMockRecorder {
	return m.recorder
}

// Close mocks base method
func (m *MockIKeyBucket) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close
func (mr *MockIKeyBucketMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockIKeyBucket)(nil).Close))
}

// Publish mocks base method
func (m *MockIKeyBucket) Publish(data interface{}) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Publish", data)
	ret0, _ := ret[0].(error)
	return ret0
}

// Publish indicates an expected call of Publish
func (mr *MockIKeyBucketMockRecorder) Publish(data interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Publish", reflect.TypeOf((*MockIKeyBucket)(nil).Publish), data)
}

// Register mocks base method
func (m *MockIKeyBucket) Register(receiver IKeyBucketReceiver) (IInterConnector, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Register", receiver)
	ret0, _ := ret[0].(IInterConnector)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Register indicates an expected call of Register
func (mr *MockIKeyBucketMockRecorder) Register(receiver interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Register", reflect.TypeOf((*MockIKeyBucket)(nil).Register), receiver)
}

// UnRegister mocks base method
func (m *MockIKeyBucket) UnRegister(key string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UnRegister", key)
	ret0, _ := ret[0].(error)
	return ret0
}

// UnRegister indicates an expected call of UnRegister
func (mr *MockIKeyBucketMockRecorder) UnRegister(key interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UnRegister", reflect.TypeOf((*MockIKeyBucket)(nil).UnRegister), key)
}
